project_id = "bftzfisrcivhgiejxtla"

[functions.extract-edital]
verify_jwt = false

[functions.fetch-focus]
verify_jwt = false

[functions.extract-patrimonial]
verify_jwt = false

[functions.correcao-monetaria]
verify_jwt = false
