project_id = "bftzfisrcivhgiejxtla"

[functions.lidderar-proxy]
verify_jwt = false

[functions.lidderar-auth]
verify_jwt = false

[functions.extract-edital]
verify_jwt = false

[functions.fetch-focus]
verify_jwt = false
